### ISSUE TITLE
Error when path to video contains spaces

### ISSUE THREAD

**Issue by gersonsosa** [Who8MyLunch/NutMeg#1]
Hi,

I'm having a problem when I want to get video metadata from a file with spaces in the path

To illustrate this I made an example to get metadata from a file:

```
import os

import nutmeg

import time
import re
import datetime
from timestamp2name import timestamp


def example():
    files = [
        '/171211/Street 32/VOL/1/01.MP4',
        '/171211/Street 32/VOL/1/000000-111111.MP4',
        '/171211/Street 32/VOL/1/1816-1821.MOV',
        '/171211/Street 32/VOL/1/0500-0600.mp4'
    ]

    for f in files:
        # command
        p = nutmeg.NutmegProbe(f)

        # display
        print('f: Compatible brands: %s, duration: %s, creation_time: %s' %
              (
                  p.results.container.tags.compatible_brands,
                  p.results.container.duration,
                  p.results.streams[0].tags.creation_time
              )
              )
```
*Note the space in the file path*

When I execute this code the result is this

```
Traceback (most recent call last):
  File "nutmeg_test.py", line 73, in <module>
    example()
  File "nutmeg_test.py", line 26, in example
    p.results.container.tags.compatible_brands,
  File "/home/[username]/.local/lib/python3.5/site-packages/nutmeg/processor.py", line 182, in results
    self._capture_stdout_stderr()
  File "/home/[username]/.local/lib/python3.5/site-packages/nutmeg/processor.py", line 203, in _capture_stdout_stderr
    self._results = self.post_process()
  File "/home/[username]/.local/lib/python3.5/site-packages/nutmeg/processor.py", line 246, in post_process
    parsed = json.loads(text)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I did some tests debugging and it resulted in the file name is not being quoted so the command that nutmeg ends up executing is 

```
/usr/bin/ffprobe -hide_banner -show_format -show_streams -print_format json -i /171211/Calle 32/VOL/1/01.MP4
```
When I quote the file path using shlex.quote the problem is solved so I made a fork to integrate the change in this repository.

Please take a look at it.

**Comment by gersonsosa** [comment]
It seems that only using shlex quote doesn't allow sarge to find the file, so I added double quotes and shell=True to sarge and it works

**Comment by Who8MyLunch** [comment]
@gersonsosa  Thanks for looking into this and writing a solution.  I'll merge this in shortly.

**Comment by Who8MyLunch** [comment]
@gersonsosa I'm calling this closed, please let me know if there's more trouble.
